Repository I-BIS-company/profitSystem_ibis, pull requests merged in 2023-07, with the labels that each got.

#74 顧客編集画面の画面開発
  profit-system/src/components/organisms/form/CompanyEditForm.tsx
  profit-system/src/components/organisms/form/CompanyRegisterForm.tsx
  profit-system/src/components/pages/CompanyEdit.tsx
  profit-system/src/components/pages/CompanyRegister.tsx
  profit-system/src/components/pages/Log.tsx
Labels: 最終レビュー待ち

#79 案件登録画面の画面開発
  profit-system/src/components/atoms/item/ProjectCostItem.tsx
  profit-system/src/components/molecules/container/FormButtonContainer.tsx
  profit-system/src/components/molecules/container/MainContentContainer.tsx
  profit-system/src/components/organisms/ProjectForm.tsx
  profit-system/src/components/pages/ProjectRegister.tsx
Labels: 最終レビュー待ち

#75 工数登録画面の画面開発
  profit-system/src/components/atoms/button/SecondaryButton.tsx
  profit-system/src/components/molecules/container/FormButtonContainer.tsx
  profit-system/src/components/molecules/form/ProjectForm.tsx
  profit-system/src/components/molecules/form/WorkhourForm.tsx
  profit-system/src/components/organisms/ProjectForm.tsx
  profit-system/src/components/organisms/WorkhourRegisterForm.tsx
  profit-system/src/components/pages/WorkhourRegister.tsx
Labels: 最終レビュー待ち

#81 工数編集画面の画面開発
  profit-system/src/components/molecules/form/ProjectSelectForm.tsx
  profit-system/src/components/molecules/form/WorkhourSelectForm.tsx
  profit-system/src/components/organisms/form/CompanyEditForm.tsx
  profit-system/src/components/organisms/form/CompanyRegisterForm.tsx
  profit-system/src/components/organisms/form/WorkhourEditForm.tsx
  profit-system/src/components/organisms/form/WorkhourRegisterForm.tsx
  profit-system/src/components/pages/CompanyEdit.tsx
  profit-system/src/components/pages/CompanyRegister.tsx
  profit-system/src/components/pages/ProjectsList.tsx
  profit-system/src/components/pages/WorkhourEdit.tsx
  profit-system/src/components/pages/WorkhourRegister.tsx
Labels: 最終レビュー待ち

#90 ユーザ一覧画面の画面開発
  profit-system/src/components/molecules/list/UsersTableTemplateList.tsx
  profit-system/src/components/pages/UsersList.tsx
Labels: 最終レビュー待ち

#93 工数編集画面のファイルをMainにマージ
  profit-system/src/components/molecules/form/ProjectSelectForm.tsx
  profit-system/src/components/molecules/form/WorkhourSelectForm.tsx
  profit-system/src/components/organisms/form/CompanyEditForm.tsx
  profit-system/src/components/organisms/form/CompanyRegisterForm.tsx
  profit-system/src/components/organisms/form/WorkhourEditForm.tsx
  profit-system/src/components/organisms/form/WorkhourRegisterForm.tsx
  profit-system/src/components/pages/CompanyEdit.tsx
  profit-system/src/components/pages/CompanyRegister.tsx
  profit-system/src/components/pages/ProjectsList.tsx
  profit-system/src/components/pages/WorkhourEdit.tsx
  profit-system/src/components/pages/WorkhourRegister.tsx
Labels: レビュー待ち, 最終レビュー待ち

#89 顧客一覧画面の画面開発
  profit-system/src/components/molecules/list/CompaniesTableTemplateList.tsx
  profit-system/src/components/molecules/list/UsersTableTemplateList.tsx
  profit-system/src/components/pages/CompaniesList.tsx
  profit-system/src/components/pages/ProjectsList.tsx
  profit-system/src/components/pages/UsersList.tsx
Labels: 最終レビュー待ち

#92 ユーザ編集画面の画面開発
  profit-system/src/components/atoms/item/TableHeadItem.tsx
  profit-system/src/components/atoms/item/UserEditTableItem.tsx
  profit-system/src/components/molecules/container/FormButtonContainer.tsx
  profit-system/src/components/organisms/UserEditTable.tsx
  profit-system/src/components/organisms/form/CompanyEditForm.tsx
  profit-system/src/components/pages/UserEdit.tsx
Labels: マージOK

#94 顧客編集画面のデフォルト値開発
  profit-system/src/components/molecules/container/FormButtonContainer.tsx
  profit-system/src/components/molecules/item/PhoneFormItem.tsx
  profit-system/src/components/molecules/item/PostNumFormItem.tsx
  profit-system/src/components/molecules/item/PrimaryFormItem.tsx
  profit-system/src/components/organisms/UserEditTable.tsx
  profit-system/src/components/organisms/form/CompanyEditForm.tsx
  profit-system/src/components/organisms/form/CompanyRegisterForm.tsx
  profit-system/src/components/organisms/form/WorkhourEditForm.tsx
  profit-system/src/components/organisms/form/WorkhourRegisterForm.tsx
Labels: マージOK

#96 primarybuttonにiconを追加
  profit-system/src/components/atoms/button/IconButton.tsx
  profit-system/src/components/organisms/ProjectForm.tsx
  profit-system/src/components/pages/CompaniesList.tsx
  profit-system/src/components/pages/Log.tsx
  profit-system/src/components/pages/ProjectsList.tsx
Labels: マージOK

#95 案件編集画面の画面開発
  profit-system/src/components/organisms/ProjectForm.tsx
  profit-system/src/components/organisms/form/ProjectEditForm.tsx
  profit-system/src/components/organisms/form/ProjectRegisterForm.tsx
  profit-system/src/components/pages/ProjectEdit.tsx
  profit-system/src/components/pages/ProjectRegister.tsx
Labels: マージOK

#91 利益一覧画面の作成
  profit-system/src/components/molecules/item/ProfitHeadlineItem.tsx
  profit-system/src/components/molecules/item/ProfitInfoItem.tsx
  profit-system/src/components/pages/ProfitsList.tsx
Labels: マージOK

#98 Firebaseの紐づけと初期設定
  profit-system/.gitignore
  profit-system/package.json
  profit-system/yarn.lock
Labels: 最終レビュー待ち

#100 ログイン機能の開発
  profit-system/src/components/atoms/button/LoginButton.tsx
  profit-system/src/components/organisms/form/ProjectEditForm.tsx
  profit-system/src/components/organisms/form/ProjectRegisterForm.tsx
  profit-system/src/components/pages/Login.tsx
Labels: 最終レビュー待ち

#99 顧客登録画面の情報をCompanyテーブルに追加する機能を開発
  profit-system/src/components/atoms/button/PrimaryButton.tsx
  profit-system/src/components/molecules/container/FormButtonContainer.tsx
  profit-system/src/components/molecules/item/PhoneFormItem.tsx
  profit-system/src/components/molecules/item/PostNumFormItem.tsx
  profit-system/src/components/molecules/item/PrimaryFormItem.tsx
  profit-system/src/components/organisms/form/CompanyEditForm.tsx
  profit-system/src/components/organisms/form/CompanyRegisterForm.tsx
Labels: マージOK

#103 顧客一覧画面にCompanyテーブルのデータを表示する
  profit-system/src/components/molecules/list/CompaniesTableTemplateList.tsx
Labels: マージOK

#104 ログ画面の検索バー機能開発
  profit-system/src/components/atoms/box/DateSearchBox.tsx
  profit-system/src/components/pages/Log.tsx
Labels: 最終レビュー待ち

#105 顧客編集画面の情報をCompanyテーブルに更新する機能を開発
  profit-system/src/components/atoms/button/SecondaryButton.tsx
  profit-system/src/components/molecules/EditItem.tsx
  profit-system/src/components/molecules/container/FormButtonContainer.tsx
  profit-system/src/components/molecules/item/PhoneFormItem.tsx
  profit-system/src/components/molecules/item/PostNumFormItem.tsx
  profit-system/src/components/molecules/item/PrimaryFormItem.tsx
  profit-system/src/components/molecules/list/CompaniesTableTemplateList.tsx
  profit-system/src/components/organisms/form/CompanyEditForm.tsx
  profit-system/src/components/organisms/form/CompanyRegisterForm.tsx
Labels: マージOK

#106 顧客一覧画面の検索バー機能の開発
  profit-system/src/components/atoms/button/IconButton.tsx
  profit-system/src/components/atoms/button/PrimarySearchButton.tsx
  profit-system/src/components/molecules/list/CompaniesTableTemplateList.tsx
  profit-system/src/components/pages/CompaniesList.tsx
  profit-system/src/types/company/CompanyDbType.ts
Labels: マージOK

#108 案件登録画面の情報をProjectテーブルに追加する機能を開発
  profit-system/src/components/atoms/item/ProjectCostItem.tsx
  profit-system/src/components/organisms/form/ProjectRegisterForm.tsx
Labels: マージOK

#111 案件一覧画面の検索バー機能の開発
  profit-system/src/components/pages/ProjectsList.tsx
Labels: 最終レビュー待ち

#112 ヘッダーにユーザ名を表示
  profit-system/src/components/atoms/UserName.tsx
  profit-system/src/components/organisms/Header.tsx
Labels: レビュー待ち
